DROP TABLE PRODUCTS IF EXISTS;
        CREATE TABLE PRODUCTS (
          ID VARCHAR(25) PRIMARY KEY,
          NAME VARCHAR(50),
          DESCRIPTION  VARCHAR(250),
          UNIT_PRICE DECIMAL,
          MANUFACTURER VARCHAR(50),
          CATEGORY VARCHAR(50),
          CONDITION VARCHAR(50),
          UNITS_IN_STOCK BIGINT,
          UNITS_IN_ORDER BIGINT,
          DISCONTINUED BOOLEAN
        );
        
DROP TABLE CUSTOMERS IF EXISTS;
        CREATE TABLE CUSTOMERS (
          ID VARCHAR(25) PRIMARY KEY,
          NAME VARCHAR(50),
          ADDRESS VARCHAR(250),
          NO_OF_ORDERS BIGINT
        );
        
DROP TABLE USERS IF EXISTS;
		CREATE TABLE USERS(
		 	ID VARCHAR(40) PRIMARY KEY,
			USERNAME VARCHAR(30),
			PASSWORD VARCHAR(90),
			ROLE VARCHAR(20),
			ENABLE BOOLEAN
		);
		
DROP TABLE CART IF EXISTS;
		CREATE TABLE CART(
			ID VARCHAR(40) PRIMARY KEY,
		);
		
DROP TABLE CART_ITEM IF EXISTS;
		CREATE TABLE CART_ITEM(
			ID VARCHAR(40),
			PRODUCT_ID VARCHAR(40) FOREIGN KEY REFERENCES PRODUCTS(ID),
			CART_ID VARCHAR(40) FOREIGN KEY REFERENCES CART(ID),
			QUANTITY BIGINT,
			CONSTRAINT CART_ITEM_PK PRIMARY KEY(ID,CART_ID)
		);
